// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Generated at 12/23/2025 11:18:02 AM.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MyApp.EfCore;

public partial class MyDbContext : DbContext
{
    public class TableFunctionsSchemaContainer {

	}

    public TableFunctionsSchemaContainer TableFunctions { private set; get; }

    private void OnTableFunctionsCreatingPartial(ModelBuilder modelBuilder)
    {
        TableFunctions = new TableFunctionsSchemaContainer()
        {

        };
    }


}

