// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MyApp.EfCore;

public partial class MyDbContext : DbContext
{
    public class ScalarFunctionsSchemaContainer {

	}

    public ScalarFunctionsSchemaContainer ScalarFunctions { private set; get; }

    private void OnScalarFunctionsCreatingPartial(ModelBuilder modelBuilder)
    {
        ScalarFunctions = new ScalarFunctionsSchemaContainer()
        {

        };


    }


}

public static class MyDbContextScalarFunctions
{

}

