// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Generated at 12/21/2025 6:46:45 PM.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MyApp.EfCore;

public partial class MyDbContext : DbContext
{
    public class ScalarFunctionsSchemaContainer {
		public AbcScalarFunctions abc { get; init; }
		public DboScalarFunctions dbo { get; init; }
	}

    public ScalarFunctionsSchemaContainer ScalarFunctions { private set; get; }

    private void OnScalarFunctionsCreatingPartial(ModelBuilder modelBuilder)
    {
        ScalarFunctions = new ScalarFunctionsSchemaContainer()
        {
			abc = new AbcScalarFunctions { Database = Database },
			dbo = new DboScalarFunctions { Database = Database },
        };


		modelBuilder.HasDbFunction(typeof(MyDbContextScalarFunctions.abc).GetMethod(nameof(MyDbContextScalarFunctions.abc.GetHello2), new[] { typeof(String) })).HasSchema("abc");
		modelBuilder.HasDbFunction(typeof(MyDbContextScalarFunctions.dbo).GetMethod(nameof(MyDbContextScalarFunctions.dbo.GetHello), new[] { typeof(String) })).HasSchema("dbo");
    }

	public class AbcScalarFunctions
	{
		public DatabaseFacade Database { get; init; }

		public String GetHello2(String )
		{
			var parameters = new SqlParameter[]
			{
				new SqlParameter("",  ?? (object) DBNull.Value),
			};
			return this.Database.SqlQueryRaw<String>("SELECT abc.GetHello2() AS [Value]", parameters).First();
		}
	}

	public class DboScalarFunctions
	{
		public DatabaseFacade Database { get; init; }

		public String GetHello(String )
		{
			var parameters = new SqlParameter[]
			{
				new SqlParameter("",  ?? (object) DBNull.Value),
			};
			return this.Database.SqlQueryRaw<String>("SELECT dbo.GetHello() AS [Value]", parameters).First();
		}
	}


}

public static class MyDbContextScalarFunctions
{
	public static class abc
	{
		public static String GetHello2(String ) => throw new NotSupportedException();
	}
	public static class dbo
	{
		public static String GetHello(String ) => throw new NotSupportedException();
	}

}

