// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MyApp.EfCore;

public partial class MyDbContext : DbContext
{
    public static class TableOutputTypes
    {
		public static class dbo
		{
			public class GetAllBrands_Result
			{
				public Int32 brand_id { get; set; }
				public String brand_name { get; set; }
			}

			public class GetBrandsByIds_Result
			{
				public Int32 BrandId { get; set; }
				public String BrandName { get; set; }
			}

			public class GetBrandsData_Result
			{
				public Int32 BrandId { get; set; }
				public String BrandName { get; set; }
				public Int32? Id { get; set; }
				public String Description { get; set; }
			}

			public class GetBrandsWithDescription_Result
			{
				public Int32 BrandId { get; set; }
				public String BrandName { get; set; }
				public String Description { get; set; }
			}

			public class MyFunction_Result
			{
				public Int32? Id { get; set; }
				public String Name { get; set; }
			}

		}

		public static class xyz
		{
			public class GetAllBrands_Result
			{
				public Int32 brand_id { get; set; }
				public String brand_name { get; set; }
			}

		}


    }
}
