// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Generated at 1/6/2026 8:11:25 PM.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BikesStore.Database.Tests;

public partial class MyDbContext : DbContext
{
    public static class TableOutputTypes
    {
		public static class xyz
		{
			[Keyless]
			public class GetActions_Result
			{
				public Byte? Id { get; set; }
				public String Name { get; set; }
			}

			[Keyless]
			public class GetMainActions_Result
			{
				public Byte Id { get; set; }
				public String Name { get; set; }
			}

		}


    }
}
