// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Generated at 1/6/2026 8:11:27 PM.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BikesStore.Database.Tests;

public partial class MyDbContext : DbContext
{
    public class TableFunctionsSchemaContainer {
		public XyzTableFunctions xyz { get; init; }
	}

    public TableFunctionsSchemaContainer TableFunctions { private set; get; }

    private void OnTableFunctionsCreatingPartial(ModelBuilder modelBuilder)
    {
        TableFunctions = new TableFunctionsSchemaContainer()
        {
			xyz = new XyzTableFunctions { Database = Database },
        };
    }

	public class XyzTableFunctions
	{
		public DatabaseFacade Database { get; init; }

		public IQueryable<MyDbContext.TableOutputTypes.xyz.GetActions_Result> GetActions()
		{
			var parameters = new SqlParameter[]
			{
			};
			return this.Database.SqlQueryRaw<MyDbContext.TableOutputTypes.xyz.GetActions_Result>("SELECT * FROM xyz.GetActions()", parameters);
		}

		public IQueryable<MyDbContext.TableOutputTypes.xyz.GetMainActions_Result> GetMainActions(Byte? @Id)
		{
			var parameters = new SqlParameter[]
			{
				new SqlParameter("@Id", @Id ?? (object) DBNull.Value),
			};
			return this.Database.SqlQueryRaw<MyDbContext.TableOutputTypes.xyz.GetMainActions_Result>("SELECT * FROM xyz.GetMainActions(@Id)", parameters);
		}
	}


}

