// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator.
//  Generated at 1/6/2026 8:11:28 PM.
//  Warning: Do not make changes directly to this file; they will get overwritten on the next code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BikesStore.Database.Tests;

public partial class MyDbContext : DbContext
{
    public class ScalarFunctionsSchemaContainer {
		public AbcScalarFunctions abc { get; init; }
		public DboScalarFunctions dbo { get; init; }
	}

    public ScalarFunctionsSchemaContainer ScalarFunctions { private set; get; }

    private void OnScalarFunctionsCreatingPartial(ModelBuilder modelBuilder)
    {
        ScalarFunctions = new ScalarFunctionsSchemaContainer()
        {
			abc = new AbcScalarFunctions { Database = Database },
			dbo = new DboScalarFunctions { Database = Database },
        };


		modelBuilder.HasDbFunction(typeof(MyDbContextScalarFunctions.abc).GetMethod(nameof(MyDbContextScalarFunctions.abc.GetHello2), new[] { typeof(String) })).HasSchema("abc");
		modelBuilder.HasDbFunction(typeof(MyDbContextScalarFunctions.dbo).GetMethod(nameof(MyDbContextScalarFunctions.dbo.GetHello), new[] { typeof(String), typeof(String) })).HasSchema("dbo");
    }

	public class AbcScalarFunctions
	{
		public DatabaseFacade Database { get; init; }

		public String GetHello2(String @input)
		{
			var parameters = new SqlParameter[]
			{
				new SqlParameter("@input", @input ?? (object) DBNull.Value),
			};
			return this.Database.SqlQueryRaw<String>("SELECT abc.GetHello2(@input) AS [Value]", parameters).First();
		}
	}

	public class DboScalarFunctions
	{
		public DatabaseFacade Database { get; init; }

		public String GetHello(String @input1, String @input2)
		{
			var parameters = new SqlParameter[]
			{
				new SqlParameter("@input1", @input1 ?? (object) DBNull.Value),
				new SqlParameter("@input2", @input2 ?? (object) DBNull.Value),
			};
			return this.Database.SqlQueryRaw<String>("SELECT dbo.GetHello(@input1, @input2) AS [Value]", parameters).First();
		}
	}


}

public static class MyDbContextScalarFunctions
{
	public static class abc
	{
		public static String GetHello2(String @input) => throw new NotSupportedException();
	}
	public static class dbo
	{
		public static String GetHello(String @input1, String @input2) => throw new NotSupportedException();
	}

}

