				SELECT
					r.ROUTINE_SCHEMA AS [function_schema],
					r.ROUTINE_NAME AS [function_name], 
					r.DATA_TYPE AS [function_type], 
					p.PARAMETER_NAME AS [parameter_name],
					p.DATA_TYPE AS [parameter_type],
					p.USER_DEFINED_TYPE_SCHEMA AS [type_schema],
					p.USER_DEFINED_TYPE_NAME AS [type_name]
					--r.*
				FROM INFORMATION_SCHEMA.ROUTINES r
				LEFT JOIN INFORMATION_SCHEMA.PARAMETERS p 
                    ON r.ROUTINE_SCHEMA = p.SPECIFIC_SCHEMA AND r.ROUTINE_NAME = p.SPECIFIC_NAME AND p.PARAMETER_MODE = 'IN'
				WHERE r.ROUTINE_TYPE = 'FUNCTION'
					AND r.DATA_TYPE != 'TABLE'
					AND NOT EXISTS (
						SELECT 1 
						FROM INFORMATION_SCHEMA.PARAMETERS 
						WHERE SPECIFIC_SCHEMA = p.SPECIFIC_SCHEMA AND SPECIFIC_NAME = p.SPECIFIC_NAME AND PARAMETER_MODE = 'IN' --AND DATA_TYPE IN ({ExcludedSqlTypesAsString})
					)
				ORDER BY p.SPECIFIC_SCHEMA, p.SPECIFIC_NAME, p.ORDINAL_POSITION