SELECT 
    c.TABLE_SCHEMA AS [type_schema],
    c.TABLE_NAME AS [type_name],
    c.COLUMN_NAME AS [column_name],
    c.DATA_TYPE AS [column_type],
    c.IS_NULLABLE AS [is_nullable]
FROM INFORMATION_SCHEMA.ROUTINES r
INNER JOIN INFORMATION_SCHEMA.ROUTINE_COLUMNS c ON r.ROUTINE_SCHEMA = c.TABLE_SCHEMA AND r.ROUTINE_NAME = c.TABLE_NAME
WHERE r.ROUTINE_TYPE = 'FUNCTION'
ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION


SELECT 
    r.ROUTINE_SCHEMA,
    r.ROUTINE_NAME, 
    p.PARAMETER_NAME,
    p.DATA_TYPE,
    p.USER_DEFINED_TYPE_SCHEMA,
    p.USER_DEFINED_TYPE_NAME,
    p.*
FROM INFORMATION_SCHEMA.ROUTINES r
INNER JOIN INFORMATION_SCHEMA.PARAMETERS p ON r.ROUTINE_SCHEMA = p.SPECIFIC_SCHEMA AND r.ROUTINE_NAME = p.SPECIFIC_NAME
WHERE r.ROUTINE_TYPE = 'FUNCTION' AND p.PARAMETER_MODE = 'IN'
ORDER BY p.SPECIFIC_SCHEMA, p.SPECIFIC_NAME, p.ORDINAL_POSITION